name: 'branch deploy demo'

# The workflow to execute on is comments that are newly created
on:
    issue_comment:
        types: [created]

# Permissions needed for reacting and adding comments for IssueOps commands
permissions:
    pull-requests: write
    deployments: write
    contents: write
    checks: read

jobs:
    compare:
        name: Compare Files
        if: ${{ github.event.issue.pull_request }}
        runs-on: ubuntu-latest
        steps:
            - name: branch-deploy
              uses: github/branch-deploy@v8.0.0
              with:
                  trigger: '.deploy'
                  noop_trigger: '.noop'

            - name: Check Changed Files
              id: changed-files
              run: |
                compare_url="https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files"
                files_changed=$(curl -s -X GET -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "$compare_url" | jq -r '.[].filename')

                if [ -z "$files_changed" ]; then
                    echo "No files changed in the pull request."
                    exit 0  # Exit successfully, as there are no changes to process.
                fi
                echo "$files_changed"