name: 'branch deploy demo'

# The workflow to execute on is comments that are newly created
on:
    pull_request:
        types: [closed]
    issue_comment:
        types: [created]

# Permissions needed for reacting and adding comments for IssueOps commands
permissions:
    pull-requests: write
    deployments: write
    contents: write
    checks: read

jobs:
    compare:
        runs-on: ubuntu-latest
        steps:
            - name: Check if comment contains ".QA"
              run: |
                comment=${{github.event.comment.body}}
                if echo "$comment" | grep -q ".QA"; then
                    echo "$QA=true" >> "$GITHUB_ENV"
                fi
            - name: Deploy to Production Branch
              if: ${{github.event.pull_request.merged == true}}
              run: echo "update to production"
        outputs:
            qa: ${{env.QA}}

    buiid:
        name: test123
        runs-on: ubuntu-latest
        needs: [compare]
        env:
            DEPLOY_TO_NOOP: ${{needs.compare.outputs.qa}}
        steps:
            - name: check QA
              if: ${{env.DEPLOY_TO_NOOP == 'true'}}
              run: echo "QA update"

