name: 'branch deploy demo'

# The workflow to execute on is comments that are newly created
on:
    pull_request:
        types: [closed]
    issue_comment:
        types: [created]

jobs:
    compare:
        runs-on: ubuntu-latest
        steps:
            - name: branch-deploy
              if: ${{ github.event.issue.pull_request && !github.event.pull_request.merged }}
              id: branch-deploy
              run: |
                comment=${{github.event.comment.body}}
                if echo "$comment" | grep -q ".QA"; then
                    echo "QA=true" >> $GITHUB_ENV
                else
                    exit 1
                fi
        outputs:
            qa: ${{env.QA}}

    buiid:
        name: test123
        runs-on: ubuntu-latest
        needs: [compare]
        env:
            DEPLOY_TO_QA: ${{needs.compare.outputs.qa}}
        steps:
            - name: check QA
              if: ${{env.DEPLOY_TO_QA == 'true'}}
              run: echo "QA update"

            - name: Deploy to Production Branch
              if: ${{github.event.pull_request.merged == true}}
              run: echo "update to production"

