name: 'branch deploy demo'

# The workflow to execute on is comments that are newly created
on:
    issue_comment:
        types: [created]
    pull_request:
        types: [opened ,synchronize]
# Permissions needed for reacting and adding comments for IssueOps commands
permissions:
    pull-requests: write
    deployments: write
    contents: write
    checks: read

jobs:
    compare:
        name: Compare Files
        if: ${{ github.event_name == 'pull_request' }}
        runs-on: ubuntu-latest
        steps:
            - name: Check Changed Files
              id: changed-files
              run: |
                pr_number=${{ github.event.number }}
                repo=${{ github.repository }}
                owner=${{github.repository_owner}}
                base_sha=${{github.base_ref}}
                head_sha=${{github.head_ref}}
                github_sha=${{github.sha}}
                workflow_sha=${{github.workflow_sha}}
                event_name=${{github.event_name}}

                echo "$pr_number"
                echo "$repo"
                echo "$owner"