name: 'branch deploy demo'

# The workflow to execute on is comments that are newly created
on:
    pull_request:
        types: [closed]
    issue_comment:
        types: [created]

# Permissions needed for reacting and adding comments for IssueOps commands
permissions:
    pull-requests: write
    deployments: write
    contents: write
    checks: read

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Check if comment contains ".QA"
              run: if "github.event.comment.body == .QA"; then
                        echo "update QA"
                   fi
            - name: Deploy to Production Branch
              if: ${{github.event.pull_request.merged == true}}
              run: echo "update to production"
